### create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"sai@gmail.com",
    "password":"mlpzaq123"
}

### singin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"sai@gmail.com",
    "password":"mlpzaq123"
}

### Find a user with a given id
GET http://localhost:3000/auth/1 


### Find all users with a given email
GET http://localhost:3000/auth/?email=abc@gmail.com


### Delete a user with a given id
DELETE http://localhost:3000/auth/6


### Update a user with a given id and data
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "password":"hello"
}